### PR TITLE
made numerous changes, fixed routes(had merge conflict text), improve…

### PR DESCRIPTION
**Pull request by cenderin**
Navy Veteran here, made a bunch of html changes to fix up the ui(over use of containers etc).  Changed the website so its more responsive.  Removed conflict that got merged in routes(be sure to check this kinda stuff).  Might make some more Improvements later on, hit me up on twitter if you have something specific in mind @cenderin

### CODE REVIEW

**Comment by cenderin** [comment]
If you want me to fix those other houndci issues I will, otherwise I fixed a majority of them

**Comment by davidmolina** [comment]
That be awesome. 

Separately, unable to get the donation and blog firing up locally. Been hacking away might need a bit of help.

**Comment by cenderin** [comment]
I can't do the stripe atm since it needs an api key, I also don't see where the blog is at.  so i'm not sure.

**Comment by davidmolina** [comment]
Thanks @cenderin! Having trouble w/ the Stripe integration too. That and our blog is our two major hot fixes.

**Comment by cenderin** [comment]
Do you need more help managing this project?.  Let me know and I can help sift through pull requests and issues.  Also contribute more

**Comment by davidmolina** [comment]
Yes. Stripe. And, blog setup. Took our site down twice so definitely
another set of eyes so it's done correctly.

On Wed, Jul 1, 2015 at 12:30 PM, Michael Alexander <notifications@github.com
> wrote:

> Do you need more help managing this project?. Let me know and I can help
> sift through pull requests and issues. Also contribute more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/pull/75#issuecomment-117801490>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by cenderin** [comment]
If you want to add me as a collaborator on this project I can help out with these pull requests and issues

**Comment by davidmolina** [comment]
That be great!

**Comment by davidmolina** [comment]
@cenderin the blog is here: https://github.com/Scripore/scripore.github.io and it needs to go here: https://github.com/OperationCode/operationcode.github.io. I'm working the Stripe now--

**Pull request merged**
