### PR TITLE
Update copy for new.html.erb

### PR DESCRIPTION
**Pull request by dmarchante**
Added updated date, and cleaned up grammar and wording.

### CODE REVIEW

**Comment by charlessipe** [comment]
Nice job. I'm no punctuation expert but according to The Oatmeal, a semicolon should be used between two independent clauses. http://theoatmeal.com/comics/semicolon

**Comment by dmarchante** [comment]
Thank you. This particular statement I was not completely sure about. The rule I was applying was the internal rule based on the oatmeal. I am still not entirely clear if I used it properly. I'm leaning towards no since it can't stand alone as a compete sentence. We could just do this ". . ., which is the typical age of separation." and be done with it.

**Comment by dmarchante** [comment]
Ok. I did more research, and it is a non-defining relative clause so making it ". . . , which is the typical age of separation." would make the statement grammatically sound.

**Comment by charlessipe** [comment]
Sounds good. Thanks for looking into it.

**Comment by rickr** [comment]
@dmarchante Are we going to use this PR to address the issues in #335 ?

**Comment by dmarchante** [comment]
Yes, we will be using this #336 is there a way to merge @charlessipe changes into this one?

**Comment by dmarchante** [comment]
@rickr ignore my last comment, I have merged the two changes.

**Comment by rickr** [comment]
Can you move this from #new to pages#home as well?

**Comment by dmarchante** [comment]
@rickr I just want to make sure I understand. We are eliminating #new, and adding the code from this file into #home, correct? Also, if that is correct where on the home page to you want the content and form to show up, before the Latest News section?

**Comment by dmarchante** [comment]
Or maybe locate in place of the link?

**Comment by rickr** [comment]
For now lets just take the updated text on #new and move it to the pages#home. 

Lets see how it looks right below the 'Join Now And Get Coding' button.

**Comment by rickr** [comment]
Looks like this is being taken care of in #350 so closing this PR.

**Pull request closed without merging**
