### PR TITLE
Add markdown for Nell's blog post and add it to blog/_posts

### PR DESCRIPTION
**Pull request by jjhampton**
👀  @davidmolina @nellshamrell 
* Copied content from the earlier PR #231 over to a Jekyll blog post
* Rebuilt Jekyll blog to create generated files by running `rake jekyll:generate` from within /blog directory
 
I'm not sure why there's some Git diffed changes to the other previous blog post HTML files, but upon inspecting them in localhost while running thin server, they appear to look correct.  

I think one of the issues with building the blog is that the BLOG_POSTING_GUIDE.md doesn't mention that you have to be within the /blog directory to run `rake jekyll:generate`? Took me a while to figure that out.

### CODE REVIEW

**Comment by davidmolina** [comment]
@jjhampton Good to go? Will try again this am.

**Comment by jjhampton** [comment]
Yup, should be good to go. Feel free to pull it down and fire up the blog to double check.

**Comment by rickr** [comment]
Are you sure you based this branch off the last origin/master branch? I'm suspicious of all the changes.

**Comment by jjhampton** [comment]
@rickr I'm pretty sure I did, but I'll double-check.  But yeah, it's very strange.  I noticed that the blog posts currently being served on the live site at operationcode.org/blog from May 4, May 10, May 14 (x2) and May 20 were not already generated in the public/blog directory in the latest `origin/master`.

For some reason, those are the ones that were generated when I ran `rake jekyll:generate` (in addition to the Node Summit post that I added the markdown for).

**Comment by jjhampton** [comment]
Maybe I'm unfamiliar with Jekyll, but it seems somewhat strange for the generated blog posts to be checked into source control.  I woulda thought that there would be a way to generate them during build, and only check in the Markdown files.

**Comment by rickr** [comment]
Hrm - I thought I heard @davidmolina mention he wasn't using the rake task - maybe that's what's going on? We'll be fine merging this stuff if it is indeed what's in the source directory. Can you double check that it matches what's in /blog/_drafts? Or run down the changes that were made not in this directory?

The build is a new development (:joy:) so I'm not surprised we've got a process around the blog yet. I'm OK with generating it at build time. I like the idea of having 1 source of posts.

**Comment by davidmolina** [comment]
Thanks gents. Will run it and deploy it.

**Comment by jjhampton** [comment]
I can always remove the last commit - where the rake task is run, leaving only the first commit w/ the markdown post. Is the Rails build on Heroku actually generating the Jekyll  blog post .HTML files yet?

**Comment by davidmolina** [comment]
Not yet, didn't push them up. Not showing in production.

**Comment by davidmolina** [comment]
Working..

**Comment by davidmolina** [comment]
Good fix @jjhampton. Showing now.

**Comment by davidmolina** [comment]
Pushed automatically. h/t @rickr

**Pull request merged**
