### PR TITLE
Adding Google Analytics

### PR DESCRIPTION
**Pull request by hollomancer**
Addresses #120 - who should be added to the Google Analytics account?

### CODE REVIEW

**Comment by davidmolina** [comment]
I have contact@op.... that could be used for this.

**Comment by hollomancer** [comment]
Added.

**Comment by rickr** [comment]
What are the different trackers listed? Who's account are they associated with?

**Comment by davidmolina** [comment]
Never had integrated Google analytics before.

**Comment by hollomancer** [comment]
I went ahead and created an account. Each tracker is associated with a different environment right now.

**Comment by rickr** [comment]
Who has access to the account and at what permission levels?

**Comment by hollomancer** [comment]
Just me and contact@operationcode.org, full access for both.

**Comment by davidmolina** [comment]
Someone on the Core Team want to take the contact@ account to sync micro-service efforts & accounts?

**Comment by hollomancer** [comment]
There is a security aspect to this, the more of these kind of services we adopt. Might be part of a larger conversation.

**Comment by davidmolina** [comment]
Good call. Might be worth jumping on a call to flush out. Any day this week.

**Comment by rickr** [comment]
I'm going to file another ticket to suss out who and where the host for the account should be. For now is everyone OK if I merge this in. We can change the trackers if need be in the future.

@hollomancer Any reason we have the trackers for dev and test? That doesn't seem like it would be useful data.

**Comment by hollomancer** [comment]
Didn't want to pollute production data while testing it. I can just change each ID to be the same, if you prefer.

**Comment by davidmolina** [comment]
I'm good.

**Comment by rickr** [comment]
Oh sorry I phrased that poorly. I was wondering why we need a tracker at all in dev/test environments? 

Could you just remove the tracker IDs from test/dev and only have it work in production?

**Comment by jjhampton** [comment]
I agree - Google Analytics should only be in production

**Comment by rickr** [comment]
@hollomancer I'm going to close this out as it now has merge conflicts. Can you rebase and then open a new PR when able? Thanks so much!

**Pull request closed without merging**
