### PR TITLE
Temporary fix for phone view

### PR DESCRIPTION
**Pull request by alexkaufman06**

### CODE REVIEW

**Comment by davidmolina** [comment]
@alexkaufman06 -- did you see the Hound comments?

**Comment by nellshamrell** [comment]
I think there was a bit of a delay before the hound comments showed up (bad hound!).  Would you like me to submit a pull request correcting these?

**Comment by davidmolina** [comment]
Please. Thanks!

**Comment by alexkaufman06** [comment]
I did see it.  That is a really cool feature that I wasn't aware of!  Most
of that work was done last minute on Friday.  I don't have access to a
computer until tomorrow so if you want to fix it that is fine.  Otherwise
I'll fix it tomorrow after class.

**Comment by nellshamrell** [comment]
I've got it.  Pull request coming your way!

**Comment by nellshamrell** [comment]
oh...whoops...for some reason I thought this was my pull request to make the drop down menus in the nav bar come down.  @alexkaufman06 I will leave this to you :)

**Comment by alexkaufman06** [comment]
no worries, sounds good!

**Comment by davidmolina** [comment]
Thanks @nellshamrell @alexkaufman06.

**Pull request merged**
