### PR TITLE
Update_header.html.erb

### PR DESCRIPTION
**Pull request by tadake**
added about to the nav bar

### CODE REVIEW

**Comment by davidmolina** [comment]
@tadake thanks for this contribution. Let me clean up the `/about` page in the next day or two and will merge this in when ready.

**Comment by tadake** [comment]
Your welcome!My father's a disabled veteran and  he's a programmer and is also my inspiration for coming into the field. I really think this is an amazing program.
sincerely,
kyle diazokinawa_soba@yahoo.com 


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: David Molina <notifications@github.com> Date: 5/3/2016  1:19 AM  (GMT-07:00) To: OperationCode/operationcode <operationcode@noreply.github.com> Cc: tadake <okinawa_soba@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [OperationCode/operationcode] Update_header.html.erb (#218) 
@tadake thanks for this contribution. Let me clean up the /about page in the next day or two and will merge this in when ready.

**Comment by tadake** [comment]
Also @davidmolina im pretty well versed in HTML5 CSS3 adn frmaeworks like bootstrap and materialize. If you need any thing else let me know.

**Comment by davidmolina** [comment]
@tadake Most definitely. The landing and some of the other pages needs some work. Invite to our Slack incoming.

**Comment by davidmolina** [comment]
@tadake What's your email? Get's cut off.

**Comment by tadake** [comment]
okinawa_soba@yahoo.com @davidmolina

**Comment by davidmolina** [comment]
@tadake Got my plate full today to revise... will attack this over the weekend. Feel free to pursue other ones here. Thanks.

**Comment by davidmolina** [comment]
@tadake Added an [about page](https://github.com/OperationCode/operationcode/commit/4fda198a85b16018b9ca6f4a33d3bd046e5aa838). Can you pull again so you're current and I merge this in. Thanks.

**Pull request merged**
