### PR TITLE
added transparent box to home page

### PR DESCRIPTION
**Pull request by rjcox**

### CODE REVIEW

**Comment by rjcox** [comment]
Added the spaces in the rgba argument in application.scss

**Comment by davidmolina** [comment]
Thanks @rjcox for this. @alexkaufman06 fyi.

**Comment by davidmolina** [comment]
@rjcox Going to a new UI/UX soon. May or may not merge this. Either way, can't merge this pull request. Conflicts I believe. /cc @cenderin

**Comment by emckenna** [comment]
One general comment.  This PR is HUGE.  Makes it very difficult to take it all in.  For the future, I would suggest much smaller pieces  It makes the process go faster, conflicts easier to resolve, and doesn't give you a heart attack when you see 158 files have changed. ;)

But Yes, sometimes big PRs like this can't be avoided, but when not resolved quickly they tend to rot on  the vine.

**Comment by davidmolina** [comment]
Agree. Wondering if we could pull this back, and break it down into smaller chunks. 

Also, we may need to update our contributing guideline for expectations.

**Comment by cenderin** [comment]
I would not merge this at all.  I think almost every single file would be a merge conflict.  I would re-fork and properly update the branch every now and then.  https://gist.github.com/CristinaSolana/1885435   I do believe you updated the branch but got merge conflicts on everything so you fixed that commited it all, and now its registering as changes.  So I Think you updated the fork wrong(it can be weird and confusing but do it a couple times and it would be good)

**Comment by davidmolina** [comment]
Thanks Michael.

**Comment by rickr** [comment]
Hello @rjcox,

Is it possible for you to rebase onto master? This PR is a bit out of date.

**Pull request closed without merging**
