### PR TITLE
Fix Heroku take 2

### PR DESCRIPTION
**Pull request by alexkaufman06**
Let's test this and see if the images will load.

### CODE REVIEW

**Comment by davidmolina** [comment]
@alexkaufman06 -- giving it a shot now. Hold tight.

**Comment by davidmolina** [comment]
@alexkaufman06 -- looked like it did the trick. Check out your on your iPhone 6. I'll use inspect as well. Thanks!

**Comment by alexkaufman06** [comment]
Awesome!  Looks good on my phone.  We'll have to find a way to resize the
scholarship image on mobile but it will work for now.

**Comment by davidmolina** [comment]
@alexkaufman06 -- exactly. Looks gorgeous now. Love the transparent button. Man you helped Operation Code craft a beautiful homepage! 

We can resize now/future if you have time. No rush at all.

**Comment by alexkaufman06** [comment]
Sounds good.  Not sure if I can make the launch party tonight but I'm sure
it will be awesome!

**Pull request merged**
