### PR TITLE
Add Codefellows phone number

### PR DESCRIPTION
**Pull request by charlessipe**
Trying a test of a pull request

### CODE REVIEW

**Comment by charlessipe** [comment]
I added some online code schools to the code schools page (Bloc, The Firehose Project, Tealeaf Academy).

**Comment by davidmolina** [comment]
@charlessipe - Thanks so much for your contribution! Can you please take out those .DS_store files, move the others to "Learning Resources" as they are online resources only. Also, remove number. We'd have to add numbers to all the services. Those might change more periodically than the URL. Thanks!

**Comment by davidmolina** [comment]
@nanoxd

**Comment by davidmolina** [comment]
Hmm. Why can't I merge this request?

**Comment by emckenna** [comment]
says merge conflict?  there are some DS_STORE files in the pr as well.

**Comment by emckenna** [comment]
I think @charlessipe needs to make a branch from his master?, then submit that pull request to merge to upstream master.  Not sure if that is required or not.

**Comment by davidmolina** [comment]
Think that's right. Possible @charlessipe <https://github.com/charlessipe>?

On Tue, Jul 21, 2015 at 6:57 AM, Eric Mckenna <notifications@github.com>
wrote:

> I think @charlessipe <https://github.com/charlessipe> needs to make a
> branch from his master?, then submit that pull request to merge to upstream
> master. Not sure if that is required or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/pull/1#issuecomment-123315570>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by rickr** [comment]
Hi @charlessipe, 

Looks like this PR is over a year old. Is the info still relevant? If it is can you rebase onto master and resubmit?

**Pull request closed without merging**
